Repository nuagenetworks/js-bambou, pull requests merged in 2021-02, with the labels that each got.

#185 VSD-47571 - use custom method to transform object in query response
  elasticsearch/ESTabify.js
Labels: 21.4, ready for review

#186 VSD-51867 Heatmap color changed for >10% loss and when there is no loss
  tabify/fecHeatmapTabify.js
Labels: 21.x, ready for review

#187 VSD-51867 Heatmap color changed for >10% loss and when there is no loss (#186)
  tabify/fecHeatmapTabify.js
Labels: 20.10, ready for review

#188 fix VSD-51064 - increase ES connection timeout to 120sec
  elasticsearch/ESRESTConnection.js
Labels: 20.10, ready for review

#189 VSD-51867 Fixing No Data in Heatmap
  tabify/fecHeatmapTabify.js
  tabify/utils.js
Labels: 21.x, ready for review

#190 VSD-51867 Fixing No Data in Heatmap (#189)
  tabify/fecHeatmapTabify.js
  tabify/utils.js
Labels: 20.10, ready for review

#191 fix VSD-51064 - increase ES connection timeout to 120sec (#188)
  elasticsearch/ESRESTConnection.js
Labels: 21.x, ready for review

#192 Include ES index column types from mapping response
  elasticsearch/ESRESTConnection.js
Labels: 21.x, ready for review

#193 VSD-51763 include column type from mapping response (#192)
  elasticsearch/ESRESTConnection.js
Labels: 20.10, ready for review
