Repository nuagenetworks/js-bambou, pull requests merged in 2021-05, with the labels that each got.

#196 VSD-53375 Do not clear the APIKey in updatePwd
  NUService.js
Labels: 21.x, bug

#198 Bulk delete funtionality - r20.10
  NURESTConnection.js
  NUService.js
Labels: 20.10, ready for review

#199 Bulk delete funtionality
  NURESTConnection.js
  NUService.js
Labels: 21.x, ready for review
